export const EVENTS = [
  {
    id: "debut-2004",
    year: 2004,
    date: "16 Oct 2004",
    era: "barca",
    title: "La Liga debut vs Espanyol (age 17)",
    description: "A 17-year-old Messi comes on as a substitute for Barcelona against Espanyol, becoming one of the club's youngest-ever La Liga players. The world gets its first glimpse of a generational talent.",
    youtubeId: "",
    youtubeSearch: "Messi first Barcelona La Liga debut Espanyol 2004",
    tweetUrl: "",
    xSearch: "Messi debut Barcelona Espanyol 2004"
  },
  {
    id: "first-goal-2005",
    year: 2005,
    date: "1 May 2005",
    era: "barca",
    title: "First senior goal, assisted by Ronaldinho",
    description: "Messi scores his first competitive goal for Barcelona against Albacete, set up by a sublime chip from Ronaldinho. At 17 years and 10 months, he becomes the youngest Barça scorer in La Liga history at the time.",
    youtubeId: "",
    youtubeSearch: "Messi first goal Barcelona Albacete Ronaldinho 2005",
    tweetUrl: "",
    xSearch: "Messi first Barcelona goal Ronaldinho 2005"
  },
  {
    id: "u20-world-cup-2005",
    year: 2005,
    date: "Jun 2005",
    era: "argentina",
    title: "FIFA U-20 World Cup — Golden Ball & Golden Boot",
    description: "Messi leads Argentina to the FIFA World Youth Championship title in the Netherlands, finishing as the tournament's top scorer and best player. It is the first major trophy of his career and a sign of things to come on the international stage.",
    youtubeId: "",
    youtubeSearch: "Messi FIFA U20 World Cup 2005 Argentina Golden Boot",
    tweetUrl: "",
    xSearch: "Messi U20 World Cup Argentina 2005 Golden Ball"
  },
  {
    id: "first-world-cup-2006",
    year: 2006,
    date: "Jun 2006",
    era: "argentina",
    title: "First FIFA World Cup — scores debut goal at age 18",
    description: "Messi makes his senior World Cup debut in Germany, coming off the bench to score against Serbia & Montenegro and become one of Argentina's youngest-ever World Cup scorers. Argentina reach the quarter-finals before losing to Germany on penalties — the first of many international heartbreaks.",
    youtubeId: "",
    youtubeSearch: "Messi first World Cup goal 2006 Germany Serbia Montenegro",
    tweetUrl: "",
    xSearch: "Messi World Cup debut 2006 Germany"
  },
  {
    id: "copa-america-runner-up-2007",
    year: 2007,
    date: "15 Jul 2007",
    era: "argentina",
    title: "Copa América runner-up — wins Best Young Player",
    description: "Argentina reach the Copa América final in Venezuela but are outclassed by Brazil 3–0. A 19-year-old Messi is named Best Young Player of the tournament — brilliant individually, but the pattern of international near-misses is already beginning to form.",
    youtubeId: "",
    youtubeSearch: "Messi Copa America 2007 Argentina Brazil final",
    tweetUrl: "",
    xSearch: "Messi Copa America 2007 runner-up"
  },
  {
    id: "maradona-goal-2007",
    year: 2007,
    date: "18 Apr 2007",
    era: "barca",
    title: "The 'Maradona Goal' vs Getafe",
    description: "Messi picks up the ball in his own half and dribbles past five Getafe players before rounding the goalkeeper — a goal so reminiscent of Maradona's 1986 World Cup masterpiece that it instantly enters football folklore.",
    youtubeId: "",
    youtubeSearch: "Messi goal vs Getafe 2007 Maradona Copa del Rey",
    tweetUrl: "",
    xSearch: "Messi Maradona goal Getafe 2007"
  },
  {
    id: "olympic-gold-2008",
    year: 2008,
    date: "23 Aug 2008",
    era: "argentina",
    title: "Olympic Gold Medal — Beijing",
    description: "Messi helps Argentina win the gold medal at the Beijing Olympics, one of the few international trophies he would hold for the next 13 years. Ángel Di María scores the only goal in a 1–0 final win over Nigeria, with Messi — two goals and multiple assists across the tournament — a constant creative force.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina Olympic gold medal Beijing 2008 Nigeria",
    tweetUrl: "",
    xSearch: "Messi Olympic gold 2008 Beijing Argentina"
  },
  {
    id: "first-treble-2009",
    year: 2009,
    date: "May 2009",
    era: "barca",
    title: "First treble, UCL final header & 1st Ballon d'Or",
    description: "Barcelona complete a historic treble under Pep Guardiola. Messi heads in the decisive second goal in the Champions League final against Manchester United in Rome, then claims his first Ballon d'Or — the beginning of an unprecedented era of individual dominance.",
    youtubeId: "",
    youtubeSearch: "Messi header Champions League final 2009 Barcelona Manchester United Rome",
    tweetUrl: "",
    xSearch: "Messi Ballon d'Or 2009 Barcelona treble"
  },
  {
    id: "club-world-cup-2009",
    year: 2009,
    date: "19 Dec 2009",
    era: "barca",
    title: "FIFA Club World Cup — completing the sextuple",
    description: "Barcelona defeat Argentine club Estudiantes de La Plata 2–1 after extra time in Abu Dhabi to become world champions. Messi scores the winning goal and is named Player of the Tournament, capping a calendar year in which Barça won six trophies — a sextuple no club has matched since.",
    youtubeId: "",
    youtubeSearch: "Messi Club World Cup 2009 Barcelona Estudiantes Abu Dhabi",
    tweetUrl: "",
    xSearch: "Messi Club World Cup 2009 Barcelona sextuple"
  },
  {
    id: "second-ballon-dor-2010",
    year: 2010,
    date: "2010",
    era: "barca",
    title: "2nd Ballon d'Or — 34 La Liga goals",
    description: "Messi wins his second Ballon d'Or for a season in which he scores 34 goals in La Liga alone, driving Barcelona to the Spanish title. At 23, the gap between him and every other player on the planet is already becoming difficult to quantify.",
    youtubeId: "",
    youtubeSearch: "Messi second Ballon d'Or 2010 award ceremony",
    tweetUrl: "",
    xSearch: "Messi 2nd Ballon d'Or 2010"
  },
  {
    id: "ucl-wembley-2011",
    year: 2011,
    date: "28 May 2011",
    era: "barca",
    title: "Champions League win vs Man Utd at Wembley",
    description: "Barcelona dismantle Manchester United 3–1 at Wembley to claim their fourth European Cup. Messi scores a stunning long-range effort and orchestrates one of the greatest club performances ever seen, cementing this Barça side as one of history's finest.",
    youtubeId: "",
    youtubeSearch: "Messi goal Barcelona Manchester United Champions League final Wembley 2011",
    tweetUrl: "",
    xSearch: "Messi Champions League final Wembley 2011"
  },
  {
    id: "third-ballon-dor-2011",
    year: 2011,
    date: "2011",
    era: "barca",
    title: "3rd consecutive Ballon d'Or",
    description: "A third straight Ballon d'Or confirms Messi's complete dominance of world football. He finishes the 2010–11 season with 53 goals in all competitions — a new personal record — and is the driving force behind Barça's Champions League triumph at Wembley.",
    youtubeId: "",
    youtubeSearch: "Messi third Ballon d'Or 2011 ceremony award",
    tweetUrl: "",
    xSearch: "Messi 3rd Ballon d'Or 2011"
  },
  {
    id: "91-goals-2012",
    year: 2012,
    date: "Dec 2012",
    era: "barca",
    title: "Record 91 goals in a calendar year",
    description: "Messi shatters Gerd Müller's 40-year-old record of 85 goals in a calendar year, finishing 2012 with an almost incomprehensible 91 goals in all competitions. The record still stands.",
    youtubeId: "",
    youtubeSearch: "Messi 91 goals calendar year 2012 record Gerd Muller",
    tweetUrl: "",
    xSearch: "Messi 91 goals 2012 record"
  },
  {
    id: "fourth-ballon-dor-2012",
    year: 2012,
    date: "2012",
    era: "barca",
    title: "4th consecutive Ballon d'Or — first ever",
    description: "Messi wins his fourth consecutive Ballon d'Or, becoming the first player in history to win the award four times in a row. The 2009–2012 run of dominance remains unmatched in the award's history.",
    youtubeId: "",
    youtubeSearch: "Messi fourth Ballon d'Or 2012 award ceremony",
    tweetUrl: "",
    xSearch: "Messi 4th Ballon d'Or 2012"
  },
  {
    id: "world-cup-final-2014",
    year: 2014,
    date: "13 Jul 2014",
    era: "argentina",
    title: "World Cup final runner-up; wins Golden Ball",
    description: "Argentina reach the World Cup final in Brazil, losing 1–0 to Germany in extra time. Messi carries his nation through the tournament with a string of match-winning performances and is awarded the Golden Ball as the tournament's best player — though the outcome remains the bitterest chapter of his international career.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina World Cup final 2014 Brazil Germany Golden Ball",
    tweetUrl: "",
    xSearch: "Messi World Cup final 2014 Argentina Golden Ball"
  },
  {
    id: "second-treble-2015",
    year: 2015,
    date: "Jun 2015",
    era: "barca",
    title: "Second treble & 5th Ballon d'Or",
    description: "Barcelona win La Liga, the Copa del Rey, and the Champions League again under Luis Enrique, with Messi, Suárez, and Neymar forming the most feared attack in the world. A 5th Ballon d'Or follows, equalling Cristiano Ronaldo's tally at the time.",
    youtubeId: "",
    youtubeSearch: "Messi Barcelona treble 2015 Champions League Berlin",
    tweetUrl: "",
    xSearch: "Messi 5th Ballon d'Or 2015 Barcelona treble"
  },
  {
    id: "copa-america-runner-up-2015",
    year: 2015,
    date: "4 Jul 2015",
    era: "argentina",
    title: "Copa América runner-up — second final defeat to Chile",
    description: "Argentina reach yet another Copa América final but lose to Chile on penalties for the first time, in Santiago. Messi scores in the shootout but two teammates miss, and Argentina's international drought stretches on. A second consecutive major final defeat intensifies questions about whether the trophy will ever arrive.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina Copa America final 2015 Chile penalties",
    tweetUrl: "",
    xSearch: "Messi Copa America 2015 final Argentina Chile"
  },
  {
    id: "club-world-cup-2015",
    year: 2015,
    date: "20 Dec 2015",
    era: "barca",
    title: "Second FIFA Club World Cup — Player of the Tournament",
    description: "Barcelona beat River Plate 3–0 in Yokohama to win the Club World Cup for the second time, with Messi collecting the Golden Ball as player of the tournament. It is a fitting final chapter to a treble-winning year and Barça's most decorated era.",
    youtubeId: "",
    youtubeSearch: "Messi Club World Cup 2015 Barcelona River Plate Yokohama",
    tweetUrl: "",
    xSearch: "Messi Club World Cup 2015 Barcelona"
  },
  {
    id: "copa-america-centenario-2016",
    year: 2016,
    date: "26 Jun 2016",
    era: "argentina",
    title: "Copa América Centenario runner-up — brief retirement",
    description: "Argentina lose a third consecutive final to Chile on penalties in New Jersey. Messi misses his spot-kick and announces his international retirement in tears. The football world reacts with an outpouring of support — 'Don't go, Leo' — and he reverses the decision within weeks, eventually fulfilling his destiny in Qatar.",
    youtubeId: "",
    youtubeSearch: "Messi Copa America Centenario 2016 final retirement announcement Argentina Chile",
    tweetUrl: "",
    xSearch: "Messi retirement announcement Copa America 2016"
  },
  {
    id: "ucl-semi-liverpool-2019",
    year: 2019,
    date: "30 Apr 2019",
    era: "barca",
    title: "UCL semi vs Liverpool — Messi's free-kick & Anfield collapse",
    description: "Messi scores twice in the first leg at the Camp Nou — including a stunning direct free-kick — as Barcelona lead 3–0 going to Anfield. But in one of football's most extraordinary nights, Liverpool win the second leg 4–0 to reach the final on aggregate. The result stands as one of the most painful defeats of Messi's career.",
    youtubeId: "",
    youtubeSearch: "Messi free kick Barcelona Liverpool Champions League semi 2019",
    tweetUrl: "",
    xSearch: "Messi Liverpool UCL semi 2019 Anfield comeback"
  },
  {
    id: "sixth-ballon-dor-2019",
    year: 2019,
    date: "2019",
    era: "barca",
    title: "6th Ballon d'Or — a new record",
    description: "Messi claims his sixth Ballon d'Or, surpassing Cristiano Ronaldo's five to set a new record for the most wins in the award's history. He finishes La Liga as top scorer and drives Barcelona's domestic campaign almost single-handedly.",
    youtubeId: "",
    youtubeSearch: "Messi 6th Ballon d'Or 2019 record ceremony",
    tweetUrl: "",
    xSearch: "Messi 6th Ballon d'Or 2019"
  },
  {
    id: "copa-america-2021",
    year: 2021,
    date: "10 Jul 2021",
    era: "argentina",
    title: "Copa América — first senior international trophy",
    description: "After coming agonisingly close multiple times, Messi finally lifts a major trophy with Argentina, winning the Copa América in Brazil. He is named Player of the Tournament with four goals and five assists, ending years of heartbreak on the international stage.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina Copa America 2021 champion trophy Brazil",
    tweetUrl: "",
    xSearch: "Messi Copa America 2021 Argentina trophy"
  },
  {
    id: "barca-farewell-2021",
    year: 2021,
    date: "8 Aug 2021",
    era: "psg",
    title: "Tearful Barcelona farewell; joins Paris Saint-Germain",
    description: "In an emotional press conference, a tearful Messi announces he is leaving Barcelona after 21 years — financial fair play regulations made his renewal impossible. Days later he signs for Paris Saint-Germain, ending the most celebrated club career in one city the sport has ever seen.",
    youtubeId: "",
    youtubeSearch: "Messi farewell Barcelona press conference crying 2021",
    tweetUrl: "",
    xSearch: "Messi farewell Barcelona 2021 PSG signing"
  },
  {
    id: "seventh-ballon-dor-2021",
    year: 2021,
    date: "Nov 2021",
    era: "argentina",
    title: "7th Ballon d'Or",
    description: "Riding the wave of Argentina's Copa América triumph, Messi collects his seventh Ballon d'Or — extending his own world record and silencing those who had questioned his international legacy.",
    youtubeId: "",
    youtubeSearch: "Messi 7th Ballon d'Or 2021 ceremony",
    tweetUrl: "",
    xSearch: "Messi 7th Ballon d'Or 2021"
  },
  {
    id: "psg-ligue1-2022",
    year: 2022,
    date: "May 2022",
    era: "psg",
    title: "Ligue 1 title with PSG",
    description: "Messi wins his first and only Ligue 1 championship as Paris Saint-Germain seal the French title. His debut season in Paris is difficult by his own standards — hampered by injury and COVID — but the league medal adds to a collection that now spans every major domestic league he has played in.",
    youtubeId: "",
    youtubeSearch: "Messi PSG Ligue 1 champion 2022",
    tweetUrl: "",
    xSearch: "Messi PSG Ligue 1 title 2022"
  },
  {
    id: "world-cup-2022",
    year: 2022,
    date: "18 Dec 2022",
    era: "argentina",
    title: "FIFA World Cup champion — scores in the final",
    description: "In what many call the greatest World Cup final ever played, Messi scores twice as Argentina beat France on penalties in Qatar. He finishes with seven goals and three assists across the tournament, claiming a second Golden Ball and completing the one trophy that had eluded him his entire career.",
    youtubeId: "",
    youtubeSearch: "Messi World Cup final 2022 Qatar Argentina France goal",
    tweetUrl: "",
    xSearch: "Messi World Cup champion 2022 Argentina Qatar"
  },
  {
    id: "miami-debut-2023",
    year: 2023,
    date: "21 Jul 2023",
    era: "miami",
    title: "Inter Miami debut — free-kick winner vs Cruz Azul",
    description: "Messi makes his Inter Miami debut in the Leagues Cup and wins the match with a curling free-kick in stoppage time. The strike triggers delirious scenes at DRV PNK Stadium and announces the dawn of a new era for American soccer.",
    youtubeId: "",
    youtubeSearch: "Messi Inter Miami debut free kick Cruz Azul Leagues Cup 2023",
    tweetUrl: "",
    xSearch: "Messi Inter Miami debut Cruz Azul 2023 free kick"
  },
  {
    id: "leagues-cup-2023",
    year: 2023,
    date: "19 Aug 2023",
    era: "miami",
    title: "Wins Leagues Cup — first Inter Miami trophy",
    description: "Inter Miami lift the Leagues Cup, their first-ever major trophy, with Messi as the architect. He scores in the final and finishes the tournament with 10 goals in 7 games, transforming a struggling club into a continental champion almost overnight.",
    youtubeId: "",
    youtubeSearch: "Messi Inter Miami Leagues Cup final 2023 trophy",
    tweetUrl: "",
    xSearch: "Messi Leagues Cup Inter Miami 2023"
  },
  {
    id: "eighth-ballon-dor-2023",
    year: 2023,
    date: "30 Oct 2023",
    era: "miami",
    title: "Record-extending 8th Ballon d'Or",
    description: "Messi claims an unprecedented eighth Ballon d'Or, recognised primarily for his World Cup-winning year with Argentina. At 36 years old, he continues to rewrite the history books in a sport that once seemed to have no more records left to break.",
    youtubeId: "",
    youtubeSearch: "Messi 8th Ballon d'Or 2023 ceremony record",
    tweetUrl: "",
    xSearch: "Messi 8th Ballon d'Or 2023 record"
  },
  {
    id: "copa-america-2024",
    year: 2024,
    date: "14 Jul 2024",
    era: "argentina",
    title: "Copa América 2024 — champion despite injury",
    description: "Argentina retain the Copa América on US soil, with Messi hobbling off injured in the final. Despite his absence for much of the decisive match, his leadership through the tournament proves pivotal as La Albiceleste defend their continental crown.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina Copa America 2024 champion final injury",
    tweetUrl: "",
    xSearch: "Messi Copa America 2024 Argentina champion"
  },
  {
    id: "supporters-shield-2024",
    year: 2024,
    date: "2024",
    era: "miami",
    title: "Supporters' Shield, record points & first MLS MVP",
    description: "Inter Miami win the Supporters' Shield with a record-breaking regular season points tally, and Messi is named MLS Most Valuable Player — the first time the award has gone to a player of his pedigree. He proves that MLS is not a retirement league.",
    youtubeId: "",
    youtubeSearch: "Messi MLS MVP 2024 Inter Miami Supporters Shield",
    tweetUrl: "",
    xSearch: "Messi MLS MVP 2024 Inter Miami Supporters Shield"
  },
  {
    id: "mls-golden-boot-2025",
    year: 2025,
    date: "18 Oct 2025",
    era: "miami",
    title: "MLS Golden Boot — 29 goals",
    description: "Messi finishes the 2025 MLS regular season as the league's top scorer with 29 goals, claiming the Golden Boot and reaffirming that even in his late 30s he remains a cut above every other player in Major League Soccer.",
    youtubeId: "",
    youtubeSearch: "Messi MLS Golden Boot 2025 top scorer 29 goals",
    tweetUrl: "",
    xSearch: "Messi MLS Golden Boot 2025"
  },
  {
    id: "mls-cup-2025",
    year: 2025,
    date: "6 Dec 2025",
    era: "miami",
    title: "First MLS Cup title & 2nd straight MLS MVP",
    description: "Inter Miami beat Vancouver Whitecaps 3–1 to lift the MLS Cup — the club's first-ever league championship. Messi is named MLS MVP for the second consecutive year, completing an extraordinary transformation of American soccer's biggest stage.",
    youtubeId: "",
    youtubeSearch: "Messi Inter Miami MLS Cup 2025 champion Vancouver",
    tweetUrl: "",
    xSearch: "Messi MLS Cup 2025 Inter Miami champion"
  },
  {
    id: "world-cup-2026",
    year: 2026,
    date: "2026",
    era: "argentina",
    title: "Looking ahead: defending the World Cup",
    description: "With the FIFA World Cup taking place in North America in 2026, Messi has a chance to do what no player has ever done — defend the World Cup on home soil (for his adopted country). The football world watches and waits.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina World Cup 2026 North America",
    tweetUrl: "",
    xSearch: "Messi Argentina World Cup 2026"
  }
];
