export const EVENTS = [
  {
    id: "debut-2004",
    year: 2004,
    date: "16 Oct 2004",
    era: "barca",
    title: "La Liga debut vs Espanyol (age 17)",
    description: "A 17-year-old Messi comes on as a substitute for Barcelona against Espanyol, becoming one of the club's youngest-ever La Liga players. The world gets its first glimpse of a generational talent.",
    youtubeId: "",
    youtubeSearch: "Messi first Barcelona La Liga debut Espanyol 2004",
    tweetUrl: "",
    xSearch: "Messi debut Barcelona Espanyol 2004"
  },
  {
    id: "first-goal-2005",
    year: 2005,
    date: "1 May 2005",
    era: "barca",
    title: "First senior goal, assisted by Ronaldinho",
    description: "Messi scores his first competitive goal for Barcelona against Albacete, set up by a sublime chip from Ronaldinho. At 17 years and 10 months, he becomes the youngest Barça scorer in La Liga history at the time.",
    youtubeId: "",
    youtubeSearch: "Messi first goal Barcelona Albacete Ronaldinho 2005",
    tweetUrl: "",
    xSearch: "Messi first Barcelona goal Ronaldinho 2005"
  },
  {
    id: "u20-world-cup-2005",
    year: 2005,
    date: "Jun 2005",
    era: "argentina",
    title: "FIFA U-20 World Cup — Golden Ball & Golden Boot",
    description: "Messi leads Argentina to the FIFA World Youth Championship title in the Netherlands, finishing as the tournament's top scorer and best player. It is the first major trophy of his career and a sign of things to come on the international stage.",
    youtubeId: "",
    youtubeSearch: "Messi FIFA U20 World Cup 2005 Argentina Golden Boot",
    tweetUrl: "",
    xSearch: "Messi U20 World Cup Argentina 2005 Golden Ball"
  },
  {
    id: "maradona-goal-2007",
    year: 2007,
    date: "18 Apr 2007",
    era: "barca",
    title: "The 'Maradona Goal' vs Getafe",
    description: "Messi picks up the ball in his own half and dribbles past five Getafe players before rounding the goalkeeper — a goal so reminiscent of Maradona's 1986 World Cup masterpiece that it instantly enters football folklore.",
    youtubeId: "",
    youtubeSearch: "Messi goal vs Getafe 2007 Maradona Copa del Rey",
    tweetUrl: "",
    xSearch: "Messi Maradona goal Getafe 2007"
  },
  {
    id: "first-treble-2009",
    year: 2009,
    date: "May 2009",
    era: "barca",
    title: "First treble, UCL final header & 1st Ballon d'Or",
    description: "Barcelona complete an historic treble under Pep Guardiola. Messi heads in the decisive second goal in the Champions League final against Manchester United in Rome, then claims his first Ballon d'Or — the beginning of an unprecedented era of individual dominance.",
    youtubeId: "",
    youtubeSearch: "Messi header Champions League final 2009 Barcelona Manchester United Rome",
    tweetUrl: "",
    xSearch: "Messi Ballon d'Or 2009 Barcelona treble"
  },
  {
    id: "ucl-wembley-2011",
    year: 2011,
    date: "28 May 2011",
    era: "barca",
    title: "Champions League win vs Man Utd at Wembley",
    description: "Barcelona dismantle Manchester United 3–1 at Wembley to claim their fourth European Cup. Messi scores a stunning long-range effort and orchestrates one of the greatest club performances ever seen, cementing this Barça side as one of history's finest.",
    youtubeId: "",
    youtubeSearch: "Messi goal Barcelona Manchester United Champions League final Wembley 2011",
    tweetUrl: "",
    xSearch: "Messi Champions League final Wembley 2011"
  },
  {
    id: "91-goals-2012",
    year: 2012,
    date: "Dec 2012",
    era: "barca",
    title: "Record 91 goals in a calendar year",
    description: "Messi shatters Gerd Müller's 40-year-old record of 85 goals in a calendar year, finishing 2012 with an almost incomprehensible 91 goals in all competitions. The record still stands.",
    youtubeId: "",
    youtubeSearch: "Messi 91 goals calendar year 2012 record Gerd Muller",
    tweetUrl: "",
    xSearch: "Messi 91 goals 2012 record"
  },
  {
    id: "fourth-ballon-dor-2012",
    year: 2012,
    date: "2012",
    era: "barca",
    title: "4th consecutive Ballon d'Or — first ever",
    description: "Messi wins his fourth consecutive Ballon d'Or, becoming the first player in history to win the award four times in a row. The 2009–2012 run of dominance remains unmatched in the award's history.",
    youtubeId: "",
    youtubeSearch: "Messi fourth Ballon d'Or 2012 award ceremony",
    tweetUrl: "",
    xSearch: "Messi 4th Ballon d'Or 2012"
  },
  {
    id: "world-cup-final-2014",
    year: 2014,
    date: "13 Jul 2014",
    era: "argentina",
    title: "World Cup final runner-up; wins Golden Ball",
    description: "Argentina reach the World Cup final in Brazil, losing 1–0 to Germany in extra time. Messi carries his nation through the tournament with a string of match-winning performances and is awarded the Golden Ball as the tournament's best player — though the outcome remains the bitterest chapter of his international career.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina World Cup final 2014 Brazil Germany Golden Ball",
    tweetUrl: "",
    xSearch: "Messi World Cup final 2014 Argentina Golden Ball"
  },
  {
    id: "second-treble-2015",
    year: 2015,
    date: "Jun 2015",
    era: "barca",
    title: "Second treble & 5th Ballon d'Or",
    description: "Barcelona win La Liga, the Copa del Rey, and the Champions League again under Luis Enrique, with Messi, Suárez, and Neymar forming the most feared attack in the world. A 5th Ballon d'Or follows, equalling Cristiano Ronaldo's tally at the time.",
    youtubeId: "",
    youtubeSearch: "Messi Barcelona treble 2015 Champions League Berlin",
    tweetUrl: "",
    xSearch: "Messi 5th Ballon d'Or 2015 Barcelona treble"
  },
  {
    id: "sixth-ballon-dor-2019",
    year: 2019,
    date: "2019",
    era: "barca",
    title: "6th Ballon d'Or — a new record",
    description: "Messi claims his sixth Ballon d'Or, surpassing Cristiano Ronaldo's five to set a new record for the most wins in the award's history. He finishes La Liga as top scorer and drives Barcelona's domestic campaign almost single-handedly.",
    youtubeId: "",
    youtubeSearch: "Messi 6th Ballon d'Or 2019 record ceremony",
    tweetUrl: "",
    xSearch: "Messi 6th Ballon d'Or 2019"
  },
  {
    id: "copa-america-2021",
    year: 2021,
    date: "10 Jul 2021",
    era: "argentina",
    title: "Copa América — first senior international trophy",
    description: "After coming agonisingly close multiple times, Messi finally lifts a major trophy with Argentina, winning the Copa América in Brazil. He is named Player of the Tournament with four goals and five assists, ending years of heartbreak on the international stage.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina Copa America 2021 champion trophy Brazil",
    tweetUrl: "",
    xSearch: "Messi Copa America 2021 Argentina trophy"
  },
  {
    id: "barca-farewell-2021",
    year: 2021,
    date: "8 Aug 2021",
    era: "psg",
    title: "Tearful Barcelona farewell; joins Paris Saint-Germain",
    description: "In an emotional press conference, a tearful Messi announces he is leaving Barcelona after 21 years — financial fair play regulations made his renewal impossible. Days later he signs for Paris Saint-Germain, ending the most celebrated club career in one city the sport has ever seen.",
    youtubeId: "",
    youtubeSearch: "Messi farewell Barcelona press conference crying 2021",
    tweetUrl: "",
    xSearch: "Messi farewell Barcelona 2021 PSG signing"
  },
  {
    id: "seventh-ballon-dor-2021",
    year: 2021,
    date: "Nov 2021",
    era: "argentina",
    title: "7th Ballon d'Or",
    description: "Riding the wave of Argentina's Copa América triumph, Messi collects his seventh Ballon d'Or — extending his own world record and silencing those who had questioned his international legacy.",
    youtubeId: "",
    youtubeSearch: "Messi 7th Ballon d'Or 2021 ceremony",
    tweetUrl: "",
    xSearch: "Messi 7th Ballon d'Or 2021"
  },
  {
    id: "world-cup-2022",
    year: 2022,
    date: "18 Dec 2022",
    era: "argentina",
    title: "FIFA World Cup champion — scores in the final",
    description: "In what many call the greatest World Cup final ever played, Messi scores twice as Argentina beat France on penalties in Qatar. He finishes with seven goals and three assists across the tournament, claiming a second Golden Ball and completing the one trophy that had eluded him his entire career.",
    youtubeId: "",
    youtubeSearch: "Messi World Cup final 2022 Qatar Argentina France goal",
    tweetUrl: "",
    xSearch: "Messi World Cup champion 2022 Argentina Qatar"
  },
  {
    id: "miami-debut-2023",
    year: 2023,
    date: "21 Jul 2023",
    era: "miami",
    title: "Inter Miami debut — free-kick winner vs Cruz Azul",
    description: "Messi makes his Inter Miami debut in the Leagues Cup and wins the match with a curling free-kick in stoppage time. The strike triggers delirious scenes at DRV PNK Stadium and announces the dawn of a new era for American soccer.",
    youtubeId: "",
    youtubeSearch: "Messi Inter Miami debut free kick Cruz Azul Leagues Cup 2023",
    tweetUrl: "",
    xSearch: "Messi Inter Miami debut Cruz Azul 2023 free kick"
  },
  {
    id: "leagues-cup-2023",
    year: 2023,
    date: "19 Aug 2023",
    era: "miami",
    title: "Wins Leagues Cup — first Inter Miami trophy",
    description: "Inter Miami lift the Leagues Cup, their first-ever major trophy, with Messi as the architect. He scores in the final and finishes the tournament with 10 goals in 7 games, transforming a struggling club into a continental champion almost overnight.",
    youtubeId: "",
    youtubeSearch: "Messi Inter Miami Leagues Cup final 2023 trophy",
    tweetUrl: "",
    xSearch: "Messi Leagues Cup Inter Miami 2023"
  },
  {
    id: "eighth-ballon-dor-2023",
    year: 2023,
    date: "30 Oct 2023",
    era: "miami",
    title: "Record-extending 8th Ballon d'Or",
    description: "Messi claims an unprecedented eighth Ballon d'Or, recognised primarily for his World Cup-winning year with Argentina. At 36 years old, he continues to rewrite the history books in a sport that once seemed to have no more records left to break.",
    youtubeId: "",
    youtubeSearch: "Messi 8th Ballon d'Or 2023 ceremony record",
    tweetUrl: "",
    xSearch: "Messi 8th Ballon d'Or 2023 record"
  },
  {
    id: "copa-america-2024",
    year: 2024,
    date: "14 Jul 2024",
    era: "argentina",
    title: "Copa América 2024 — champion despite injury",
    description: "Argentina retain the Copa América on US soil, with Messi hobbling off injured in the final. Despite his absence for much of the decisive match, his leadership through the tournament proves pivotal as La Albiceleste defend their continental crown.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina Copa America 2024 champion final injury",
    tweetUrl: "",
    xSearch: "Messi Copa America 2024 Argentina champion"
  },
  {
    id: "supporters-shield-2024",
    year: 2024,
    date: "2024",
    era: "miami",
    title: "Supporters' Shield, record points & first MLS MVP",
    description: "Inter Miami win the Supporters' Shield with a record-breaking regular season points tally, and Messi is named MLS Most Valuable Player — the first time the award has gone to a player of his pedigree. He proves that MLS is not a retirement league.",
    youtubeId: "",
    youtubeSearch: "Messi MLS MVP 2024 Inter Miami Supporters Shield",
    tweetUrl: "",
    xSearch: "Messi MLS MVP 2024 Inter Miami Supporters Shield"
  },
  {
    id: "mls-golden-boot-2025",
    year: 2025,
    date: "18 Oct 2025",
    era: "miami",
    title: "MLS Golden Boot — 29 goals",
    description: "Messi finishes the 2025 MLS regular season as the league's top scorer with 29 goals, claiming the Golden Boot and reaffirming that even in his late 30s he remains a cut above every other player in Major League Soccer.",
    youtubeId: "",
    youtubeSearch: "Messi MLS Golden Boot 2025 top scorer 29 goals",
    tweetUrl: "",
    xSearch: "Messi MLS Golden Boot 2025"
  },
  {
    id: "mls-cup-2025",
    year: 2025,
    date: "6 Dec 2025",
    era: "miami",
    title: "First MLS Cup title & 2nd straight MLS MVP",
    description: "Inter Miami beat Vancouver Whitecaps 3–1 to lift the MLS Cup — the club's first-ever league championship. Messi is named MLS MVP for the second consecutive year, completing an extraordinary transformation of American soccer's biggest stage.",
    youtubeId: "",
    youtubeSearch: "Messi Inter Miami MLS Cup 2025 champion Vancouver",
    tweetUrl: "",
    xSearch: "Messi MLS Cup 2025 Inter Miami champion"
  },
  {
    id: "world-cup-2026",
    year: 2026,
    date: "2026",
    era: "argentina",
    title: "Looking ahead: defending the World Cup",
    description: "With the FIFA World Cup taking place in North America in 2026, Messi has a chance to do what no player has ever done — defend the World Cup on home soil (for his adopted country). The football world watches and waits.",
    youtubeId: "",
    youtubeSearch: "Messi Argentina World Cup 2026 North America",
    tweetUrl: "",
    xSearch: "Messi Argentina World Cup 2026"
  }
];
